+ '<div id="'+imageId+'" class="ui special card no margin top bottom">'
+ '    <div class="blurring dimmable image">'
+ '        <div class="ui inverted dimmer">'
+ '            <div class="content">'
+ '                <div class="center">'
+ '                    <div onclick="App.modal.filemanager(\'#'+imageId+'\')" class="ui teal button icon">'
+ '                        <i class="refresh icon"></i>'
+ '                    </div>'
+ '                    <div onclick="App.tool.image.remove(\'#'+imageId+'\')" class="ui orange button icon">'
+ '                        <i class="trash outline icon"></i>'
+ '                    </div>'
+ '                </div>'
+ '            </div>'
+ '        </div>'
+ '        <img src="{!! assets('image/no-image.png') !!}" class="ui big image">'
+ '        <input name="'+imageName+'" value="" type="hidden">'
+ '    </div>'
+ '</div>'